
import { SubscriberFormData } from '@/types/subscriber';

export const initialFormData: SubscriberFormData = {
  concessionaria: 'equatorial-goias',
  subscriberType: 'person',
  personalData: {
    cpf: '',
    partnerNumber: '',
    fullName: '',
    birthDate: '',
    maritalStatus: '',
    profession: '',
    phone: '',
    email: '',
    observations: '',
    address: {
      cep: '',
      street: '',
      number: '',
      complement: '',
      neighborhood: '',
      city: '',
      state: '',
    },
    contacts: [],
  },
  companyData: {
    cnpj: '',
    partnerNumber: '',
    companyName: '',
    fantasyName: '',
    phone: '',
    email: '',
    observations: '',
    address: {
      cep: '',
      street: '',
      number: '',
      complement: '',
      neighborhood: '',
      city: '',
      state: '',
    },
    contacts: [],
  },
  administratorData: {
    cpf: '',
    fullName: '',
    birthDate: '',
    maritalStatus: '',
    profession: '',
    phone: '',
    email: '',
    address: {
      cep: '',
      street: '',
      number: '',
      complement: '',
      neighborhood: '',
      city: '',
      state: '',
    },
  },
  energyAccount: {
    holderType: 'person',
    cpfCnpj: '',
    holderName: '',
    birthDate: '',
    uc: '',
    partnerNumber: '',
    address: {
      cep: '',
      street: '',
      number: '',
      complement: '',
      neighborhood: '',
      city: '',
      state: '',
    },
  },
  titleTransfer: {
    willTransfer: false,
  },
  planContract: {
    selectedPlan: '',
    compensationMode: 'autoConsumption',
    adhesionDate: '',
    informedKwh: undefined,
    contractedKwh: undefined,
    loyalty: 'none',
    discountPercentage: undefined,
  },
  planDetails: {
    paysPisAndCofins: true,
    paysWireB: false,
    addDistributorValue: false,
    exemptFromPayment: false,
  },
  notificationSettings: {
    whatsapp: {
      sendInvoices: true,
      paymentReceived: false,
      createCharge: true,
      changeValueOrDate: true,
      oneDayBefore: true,
      onVencimentoDay: true,
      oneDayAfter: true,
      threeDaysAfter: true,
      fiveDaysAfter: true,
      sevenDaysAfter: true,
      fifteenDaysAfter: true,
      twentyDaysAfter: true,
      twentyFiveDaysAfter: true,
      thirtyDaysAfter: true,
      afterThirtyDays: true,
    },
    email: {
      createCharge: true,
      changeValueOrDate: true,
      oneDayBefore: true,
      onVencimentoDay: true,
      oneDayAfter: true,
      threeDaysAfter: true,
      fiveDaysAfter: true,
      sevenDaysAfter: true,
      fifteenDaysAfter: true,
      twentyDaysAfter: true,
      twentyFiveDaysAfter: true,
      thirtyDaysAfter: true,
      afterThirtyDays: true,
    },
  },
  attachments: {},
};
