// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axzhyfhiqlzjgckbjdwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4emh5ZmhpcWx6amdja2JqZHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTM4MzQsImV4cCI6MjA2NDYyOTgzNH0.Ccg6cGeXGoEqqjqGtub6KxBKzzdoOo5QwsxYMpCpSjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);